### ISSUE TITLE
Improve docs for key name on swift side

### ISSUE THREAD

**Issue by simonemarra** [iwantofun/shared_preferences_ios_sn#1]
Hi!

First of all I would like to thank you for this package: the suiteName parameter specification should be part of official shared_preferences plugin!

I would only keep your attention on a docs issue: it seems your plugin changes the key name, adding the prefix "flutter." + key_name.

I think it could be useful for all the other users to add a note on both Readme and pub.dev pages, but also on code docs.

I lost a couple of days trying to figure out what was wrong with my environment, XCode settings, Apple developer portal app group definitions, etc...
Than I saw the last line of your code and... "What the hell?! Am I missing a key prefix???"

Anyway... Thank you so much for the work, now I can share data from flutter/dart code to Apple Notification Service Extension swift code to manipulate push content 🥳

**Comment by iwantofun** [comment]
Thank you for your great suggestions, I will improve it when I done my works.
